/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import tela.manutencao.inse.ManutencaoInse;
import tela.manutencao.lac.ManutencaoLac;
import tela.manutencao.leite.ManutencaoLeite;
import tela.manutencao.manejo.ManutencaoManejo;
import tela.manutencao.pes.ManutencaoPes;
import tela.manutencao.raca.ManutencaoRaca;
import tela.manutencao.touro.ManutencaoTouro;
import tela.manutencao.vaca.ManutencaoVaca;

/**
 *
 * @author 8
 */
public class TelaPrincipalBovinos extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalBovinos
     */
    public TelaPrincipalBovinos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLactacao = new javax.swing.JButton();
        btnInse = new javax.swing.JButton();
        btnLeite = new javax.swing.JButton();
        btnManejo = new javax.swing.JButton();
        btnPes = new javax.swing.JButton();
        btnRaca = new javax.swing.JButton();
        btnTouro = new javax.swing.JButton();
        btnVaca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLactacao.setText("Lactação");
        btnLactacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLactacaoActionPerformed(evt);
            }
        });

        btnInse.setText("Inseminação");
        btnInse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInseActionPerformed(evt);
            }
        });

        btnLeite.setText("Produção de Leite");
        btnLeite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeiteActionPerformed(evt);
            }
        });

        btnManejo.setText("Manejo");
        btnManejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManejoActionPerformed(evt);
            }
        });

        btnPes.setText("Pessoa");
        btnPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesActionPerformed(evt);
            }
        });

        btnRaca.setText("Raça");
        btnRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacaActionPerformed(evt);
            }
        });

        btnTouro.setText("Touro");
        btnTouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTouroActionPerformed(evt);
            }
        });

        btnVaca.setText("Vaca");
        btnVaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("Garotas Unidas Jamais Serão Vencidas!!");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/ttttttttt.png"))); // NOI18N

        jLabel2.setText("Hera!");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Bovinos!!");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/eeeeeeeeeeeeeee.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Wingdings", 0, 11)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("Hera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnLactacao))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnInse))
                            .addComponent(btnLeite, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnManejo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTouro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(btnRaca)
                            .addComponent(btnPes))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLactacao)
                            .addComponent(btnPes))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInse)
                            .addComponent(btnRaca))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLeite)
                            .addComponent(btnTouro))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManejo)
                            .addComponent(btnVaca)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLactacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLactacaoActionPerformed
ManutencaoLac janela = new ManutencaoLac(this, true);
janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLactacaoActionPerformed

    private void btnInseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInseActionPerformed
ManutencaoInse janela = new ManutencaoInse(this, true);
janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnInseActionPerformed

    private void btnLeiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeiteActionPerformed
ManutencaoLeite janela = new ManutencaoLeite(this, true);
janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeiteActionPerformed

    private void btnManejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManejoActionPerformed
ManutencaoManejo janela = new ManutencaoManejo(this, true);
janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnManejoActionPerformed

    private void btnPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesActionPerformed
ManutencaoPes janela = new ManutencaoPes(this, true);
janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesActionPerformed

    private void btnRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacaActionPerformed
ManutencaoRaca janela = new ManutencaoRaca(this, true);
janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRacaActionPerformed

    private void btnTouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTouroActionPerformed
ManutencaoTouro janela = new ManutencaoTouro(this, true);
janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnTouroActionPerformed

    private void btnVacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacaActionPerformed
ManutencaoVaca janela = new ManutencaoVaca(this, true);
janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalBovinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalBovinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalBovinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalBovinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalBovinos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnInse;
    public javax.swing.JButton btnLactacao;
    public javax.swing.JButton btnLeite;
    public javax.swing.JButton btnManejo;
    public javax.swing.JButton btnPes;
    public javax.swing.JButton btnRaca;
    public javax.swing.JButton btnTouro;
    public javax.swing.JButton btnVaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
